#!/bin/bash

# Require one argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <user/repo>"
    exit 1
fi

curl --silent "https://api.github.com/repos/${1}/releases/latest" | grep -Po "(?<=\"tag_name\": \").*(?=\")"
